VirtoCommerce/vc-module-quote

VirtoCommerce.QuoteModule.Data/Services/QuoteRequestServiceImpl.cs

Paged search ordering revision

---

src/VirtoCommerce.QuoteModule.Web/ExportImport/QuoteExportImport.cs

VP-2291: Rewrite export according to V3 pattern

---

src/VirtoCommerce.QuoteModule.Web/module.manifest

https://virtocommerce.atlassian.net/browse/VP-3113

VP-3113: Fix logo

---

src/VirtoCommerce.QuoteModule.Data/Services/QuoteRequestService.cs

A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
A clear and concise description of what you want to happen.
Describe the technical details of realization provided by you.
Add any other context or screenshots about the feature request here.

VP-5334: Call ClearCache before publish event

---

src/VirtoCommerce.QuoteModule.Data/Model/QuoteRequestEntity.cs

VP-6303 36746 - Quote Address Management and Address Widget Not Refreshing
Widget is refreshing! But when we try to update the existing address we got nothing. 
Fix address path method 
Added lost part of code

VP-6303 36746 - Quote Address Management and Address Widget Not Refreshing

---

src/VirtoCommerce.QuoteModule.Web/Scripts/blades/quote-detail.js
src/VirtoCommerce.QuoteModule.Web/Scripts/blades/quote-detail.tpl.html
src/VirtoCommerce.QuoteModule.Web/module.manifest

!! store v3.10 release required !!

VP-6748: Refactor to use va-store-selector

---

src/VirtoCommerce.QuoteModule.Web/Scripts/blades/quote-assets.tpl.html
src/VirtoCommerce.QuoteModule.Web/Scripts/blades/quote-detail.js
src/VirtoCommerce.QuoteModule.Web/Scripts/blades/quote-items.js
src/VirtoCommerce.QuoteModule.Web/Scripts/blades/quote-items.tpl.html
src/VirtoCommerce.QuoteModule.Web/Scripts/blades/quotes-list.js
src/VirtoCommerce.QuoteModule.Web/Scripts/blades/quotes-list.tpl.html

VP-6770: Replace panel action icons

---

src/VirtoCommerce.QuoteModule.Core/ModuleConstants.cs

VP-6645: Change fields grouping inside Settings blade of a Store

---

src/VirtoCommerce.QuoteModule.Web/Scripts/blades/quote-assets.js
src/VirtoCommerce.QuoteModule.Web/Scripts/blades/quote-detail.js
src/VirtoCommerce.QuoteModule.Web/Scripts/blades/quote-items.js
src/VirtoCommerce.QuoteModule.Web/Scripts/blades/quotes-list.js

https://virtocommerce.atlassian.net/browse/PT-669

PT-670: Fix file-text icon

---

src/VirtoCommerce.QuoteModule.Core/Models/Address.cs
src/VirtoCommerce.QuoteModule.Core/VirtoCommerce.QuoteModule.Core.csproj
src/VirtoCommerce.QuoteModule.Data/Migrations/20210911140905_AddAddressOuterId.Designer.cs
src/VirtoCommerce.QuoteModule.Data/Migrations/20210911140905_AddAddressOuterId.cs
src/VirtoCommerce.QuoteModule.Data/Model/AddressEntity.cs
src/VirtoCommerce.QuoteModule.Web/module.manifest

Extend Address with OuterId property
https://virtocommerce.atlassian.net/browse/PT-4060

PT-4060: Extend Address with OuterId property

---

src/VirtoCommerce.QuoteModule.Core/VirtoCommerce.QuoteModule.Core.csproj
src/VirtoCommerce.QuoteModule.Data/VirtoCommerce.QuoteModule.Data.csproj
src/VirtoCommerce.QuoteModule.Web/Scripts/blades/quote-assets.js
src/VirtoCommerce.QuoteModule.Web/module.manifest

Use assets from newly created module instead of the platform
https://virtocommerce.atlassian.net/browse/PT-4135

PT-4135: Use assets from newly created module instead of the platform

---

.github/workflows/main.yml
Directory.Build.props
src/VirtoCommerce.QuoteModule.Core/VirtoCommerce.QuoteModule.Core.csproj
src/VirtoCommerce.QuoteModule.Data/Repositories/QuoteDbContext.cs
src/VirtoCommerce.QuoteModule.Data/VirtoCommerce.QuoteModule.Data.csproj
src/VirtoCommerce.QuoteModule.Web/VirtoCommerce.QuoteModule.Web.csproj
src/VirtoCommerce.QuoteModule.Web/module.manifest
tests/VirtoCommerce.QuoteModule.Tests/VirtoCommerce.QuoteModule.Tests.csproj

Bump .Net and EF up to 6
https://virtocommerce.atlassian.net/browse/PT-1956

PT-1956: Bump .Net and EF up to 6

---

src/VirtoCommerce.QuoteModule.Core/VirtoCommerce.QuoteModule.Core.csproj
src/VirtoCommerce.QuoteModule.Data/VirtoCommerce.QuoteModule.Data.csproj
src/VirtoCommerce.QuoteModule.Web/VirtoCommerce.QuoteModule.Web.csproj

PT-6404: Fix empty sonar codecoverage report

---

src/VirtoCommerce.QuoteModule.Web/Controllers/Api/QuoteModuleController.cs

Someone forgot to add produce-200 swagger annotation to the endpoint.
https://virtocommerce.atlassian.net/browse/PT-7227

PT-7227: Add produce-200 swagger annotation to the GetById endpoint

---

src/VirtoCommerce.QuoteModule.Data/Model/QuoteItemEntity.cs
src/VirtoCommerce.QuoteModule.Data/Model/QuoteRequestEntity.cs
src/VirtoCommerce.QuoteModule.Data/Model/TierPriceEntity.cs
src/VirtoCommerce.QuoteModule.Data/Repositories/QuoteRepository.cs
src/VirtoCommerce.QuoteModule.Data/Services/DefaultQuoteTotalsCalculator.cs
src/VirtoCommerce.QuoteModule.Data/Services/QuoteRequestService.cs

https://virtocommerce.atlassian.net/browse/PT-7946

PT-7946: Added missing virtual

---

src/VirtoCommerce.QuoteModule.Data/Repositories/QuoteDbContext.cs

Fix EF validation runtime warnings
https://virtocommerce.atlassian.net/browse/PT-9152

PT-9152: Fix EF validation runtime warnings

---

src/VirtoCommerce.QuoteModule.Core/Models/Search/QuoteRequestSearchCriteria.cs
src/VirtoCommerce.QuoteModule.Data/Services/QuoteRequestService.cs
src/VirtoCommerce.QuoteModule.ExperienceApi/Authorization/QuoteAuthorizationHandler.cs
src/VirtoCommerce.QuoteModule.ExperienceApi/Commands/CreateQuoteFromCartCommandHandler.cs
src/VirtoCommerce.QuoteModule.ExperienceApi/Queries/QuoteQuery.cs
src/VirtoCommerce.QuoteModule.ExperienceApi/Queries/QuoteQueryHandler.cs
src/VirtoCommerce.QuoteModule.ExperienceApi/Queries/QuotesQuery.cs
src/VirtoCommerce.QuoteModule.ExperienceApi/Queries/QuotesQueryHandler.cs
src/VirtoCommerce.QuoteModule.ExperienceApi/Validation/CartToQuoteLineItemValidationContext.cs
src/VirtoCommerce.QuoteModule.ExperienceApi/Validation/CartToQuoteLineItemValidator.cs

https://virtocommerce.atlassian.net/browse/PT-9376

PT-9376, PT-9372: simplify validation, add quote query parameters

---

src/VirtoCommerce.QuoteModule.Web/Scripts/blades/quote-detail.js

Fix opening quote blade
https://virtocommerce.atlassian.net/browse/PT-9153

PT-9153: Fix opening quote blade

---

src/VirtoCommerce.QuoteModule.Core/Models/Search/QuoteRequestSearchCriteria.cs
src/VirtoCommerce.QuoteModule.Data/Services/QuoteRequestService.cs
src/VirtoCommerce.QuoteModule.ExperienceApi/Queries/QuotesQuery.cs
src/VirtoCommerce.QuoteModule.ExperienceApi/Queries/QuotesQueryHandler.cs

```
{
quotes(storeId:"Electronics", filter: "keywordgoeshere statuses:New,Ordered createdDate:[2018-04-28 TO 2023-05-28]")
{
totalCount
items {
id
}
}
}
```
https://virtocommerce.atlassian.net/browse/PT-9408

PT-9408: add filter argument to Quotes query

---

src/VirtoCommerce.QuoteModule.Data/Services/QuoteRequestService.cs
src/VirtoCommerce.QuoteModule.ExperienceApi/Commands/ChangeQuoteCommentCommand.cs
src/VirtoCommerce.QuoteModule.ExperienceApi/Commands/ChangeQuoteCommentCommandBuilder.cs
src/VirtoCommerce.QuoteModule.ExperienceApi/Commands/ChangeQuoteCommentCommandHandler.cs
src/VirtoCommerce.QuoteModule.ExperienceApi/Commands/ChangeQuoteItemQuantityCommand.cs
src/VirtoCommerce.QuoteModule.ExperienceApi/Commands/ChangeQuoteItemQuantityCommandBuilder.cs
src/VirtoCommerce.QuoteModule.ExperienceApi/Commands/ChangeQuoteItemQuantityCommandHandler.cs
src/VirtoCommerce.QuoteModule.ExperienceApi/Commands/RemoveQuoteItemCommand.cs
src/VirtoCommerce.QuoteModule.ExperienceApi/Commands/RemoveQuoteItemCommandBuilder.cs
src/VirtoCommerce.QuoteModule.ExperienceApi/Commands/RemoveQuoteItemCommandHandler.cs
src/VirtoCommerce.QuoteModule.ExperienceApi/Commands/UpdateQuoteAddressesCommand.cs
src/VirtoCommerce.QuoteModule.ExperienceApi/Commands/UpdateQuoteAddressesCommandBuilder.cs
src/VirtoCommerce.QuoteModule.ExperienceApi/Commands/UpdateQuoteAddressesCommandHandler.cs
src/VirtoCommerce.QuoteModule.ExperienceApi/Schemas/InputQuoteAddressType.cs
src/VirtoCommerce.QuoteModule.ExperienceApi/Schemas/QuoteItemType.cs

Add new mutations:
- changeQuoteComment
- changeQuoteItemQuantity
- removeQuoteItem
- updateQuoteAddresses
https://virtocommerce.atlassian.net/browse/PT-9396

PT-9396: Add mutations for updating quotes

---

src/VirtoCommerce.QuoteModule.ExperienceApi/Schemas/InputQuoteAddressType.cs
src/VirtoCommerce.QuoteModule.ExperienceApi/Schemas/QuoteAddressType.cs

https://virtocommerce.atlassian.net/browse/PT-9933

PT-9933: add Id field in XAPI address models

---

src/VirtoCommerce.QuoteModule.ExperienceApi/Queries/QuoteQueryBuilder.cs
src/VirtoCommerce.QuoteModule.ExperienceApi/Queries/QuotesQueryBuilder.cs

https://virtocommerce.atlassian.net/browse/PT-10120

PT-10120: copy arguments in quotes queries

---

module.ignore
src/VirtoCommerce.QuoteModule.ExperienceApi/Schemas/QuoteItemType.cs
src/VirtoCommerce.QuoteModule.ExperienceApi/VirtoCommerce.QuoteModule.ExperienceApi.csproj
src/VirtoCommerce.QuoteModule.Web/module.manifest
tests/VirtoCommerce.QuoteModule.Tests/VirtoCommerce.QuoteModule.Tests.csproj

https://virtocommerce.atlassian.net/browse/PT-10888

PT-10888: Update XAPI dependency

---

src/VirtoCommerce.QuoteModule.Web/package-lock.json
src/VirtoCommerce.QuoteModule.Web/package.json
src/VirtoCommerce.QuoteModule.Web/webpack.config.js

feat: add nodejs-lts support
https://virtocommerce.atlassian.net/browse/PT-9395

PT-9395: add nodejs-lts support

---

.editorconfig
Directory.Build.props
VirtoCommerce.QuoteModule.sln.DotSettings
samples/VirtoCommerce.QuoteExtensionsModule.Web/VirtoCommerce.QuoteExtensionsModule.Web.csproj
src/VirtoCommerce.QuoteModule.Core/Models/Search/QuoteRequestSearchResult.cs
src/VirtoCommerce.QuoteModule.Core/VirtoCommerce.QuoteModule.Core.csproj
src/VirtoCommerce.QuoteModule.Data.MySql/VirtoCommerce.QuoteModule.Data.MySql.csproj
src/VirtoCommerce.QuoteModule.Data.PostgreSql/VirtoCommerce.QuoteModule.Data.PostgreSql.csproj
src/VirtoCommerce.QuoteModule.Data.SqlServer/VirtoCommerce.QuoteModule.Data.SqlServer.csproj
src/VirtoCommerce.QuoteModule.Data/Services/DefaultQuoteTotalsCalculator.cs
src/VirtoCommerce.QuoteModule.Data/Services/QuoteConverter.cs
src/VirtoCommerce.QuoteModule.Data/Services/QuoteRequestService.cs
src/VirtoCommerce.QuoteModule.Data/VirtoCommerce.QuoteModule.Data.csproj
src/VirtoCommerce.QuoteModule.ExperienceApi/Commands/CreateQuoteFromCartCommandHandler.cs
src/VirtoCommerce.QuoteModule.ExperienceApi/Commands/QuoteCommandHandler.cs
src/VirtoCommerce.QuoteModule.ExperienceApi/VirtoCommerce.QuoteModule.ExperienceApi.csproj
src/VirtoCommerce.QuoteModule.Web/Controllers/Api/QuoteModuleController.cs
src/VirtoCommerce.QuoteModule.Web/ExportImport/QuoteExportImport.cs
src/VirtoCommerce.QuoteModule.Web/Module.cs
src/VirtoCommerce.QuoteModule.Web/VirtoCommerce.QuoteModule.Web.csproj
src/VirtoCommerce.QuoteModule.Web/module.manifest
tests/VirtoCommerce.QuoteModule.Tests/VirtoCommerce.QuoteModule.Tests.csproj

https://virtocommerce.atlassian.net/browse/PT-10449

PT-10449: Use updated Crud and Search services

---

src/VirtoCommerce.QuoteModule.Web/Scripts/blades/quote-detail.tpl.html
src/VirtoCommerce.QuoteModule.Web/Scripts/blades/quotes-list.tpl.html

add filters to display dates correctly
https://virtocommerce.atlassian.net/browse/PT-14050
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.Quote_3.404.0-pr-96-286c.zip

PT-14050: add "date" filter

---

src/VirtoCommerce.QuoteModule.Data/Services/QuoteRequestService.cs

fix: 500 when user try to delete quote
https://virtocommerce.atlassian.net/browse/PT-15075
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.Quote_3.405.0-pr-98-1297.zip

PT-15075: 500 when user try to delete quote

---

Directory.Build.props
samples/VirtoCommerce.QuoteExtensionsModule.Web/VirtoCommerce.QuoteExtensionsModule.Web.csproj
src/VirtoCommerce.QuoteModule.Core/VirtoCommerce.QuoteModule.Core.csproj
src/VirtoCommerce.QuoteModule.Data.MySql/VirtoCommerce.QuoteModule.Data.MySql.csproj
src/VirtoCommerce.QuoteModule.Data.PostgreSql/VirtoCommerce.QuoteModule.Data.PostgreSql.csproj
src/VirtoCommerce.QuoteModule.Data.SqlServer/VirtoCommerce.QuoteModule.Data.SqlServer.csproj
src/VirtoCommerce.QuoteModule.Data/VirtoCommerce.QuoteModule.Data.csproj
src/VirtoCommerce.QuoteModule.ExperienceApi/VirtoCommerce.QuoteModule.ExperienceApi.csproj
src/VirtoCommerce.QuoteModule.Web/VirtoCommerce.QuoteModule.Web.csproj
src/VirtoCommerce.QuoteModule.Web/module.manifest
src/VirtoCommerce.QuoteModule.Web/package-lock.json
tests/VirtoCommerce.QuoteModule.Tests/VirtoCommerce.QuoteModule.Tests.csproj

feat: Update to net8
https://virtocommerce.atlassian.net/browse/PT-14740
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.Quote_3.800.0-pr-97-6126.zip

PT-14740: Update to net8

---

src/VirtoCommerce.QuoteModule.Data.MySql/Migrations/20240118111920_RecreateQuoteAttachmentConstraint.Designer.cs
src/VirtoCommerce.QuoteModule.Data.MySql/Migrations/20240118111920_RecreateQuoteAttachmentConstraint.cs
src/VirtoCommerce.QuoteModule.Data.MySql/Migrations/QuoteDbContextModelSnapshot.cs
src/VirtoCommerce.QuoteModule.Data.PostgreSql/Migrations/20240118110732_RecreateQuoteAttachmentConstraint.Designer.cs
src/VirtoCommerce.QuoteModule.Data.PostgreSql/Migrations/20240118110732_RecreateQuoteAttachmentConstraint.cs
src/VirtoCommerce.QuoteModule.Data.SqlServer/Migrations/20240118105941_RecreateQuoteAttachmentConstraint.Designer.cs
src/VirtoCommerce.QuoteModule.Data.SqlServer/Migrations/20240118105941_RecreateQuoteAttachmentConstraint.cs
src/VirtoCommerce.QuoteModule.Data.SqlServer/Migrations/QuoteDbContextModelSnapshot.cs
src/VirtoCommerce.QuoteModule.Data/Repositories/QuoteDbContext.cs

https://virtocommerce.atlassian.net/browse/VCST-225
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.Quote_3.801.0-pr-102-0180.zip

VCST-225: fix delete constraint

---

src/VirtoCommerce.QuoteModule.Web/Localizations/en.VirtoCommerce.Quote.json

checkbox → switch, 
tick → enable, 
remove → cancel
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.Quote_3.802.0-pr-103-77c2.zip

VCST-538: fix localization

---

src/VirtoCommerce.QuoteModule.Core/ModuleConstants.cs
src/VirtoCommerce.QuoteModule.Core/VirtoCommerce.QuoteModule.Core.csproj
src/VirtoCommerce.QuoteModule.Web/module.manifest

feat: Added public store property
https://virtocommerce.atlassian.net/browse/VCST-848
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.Quote_3.806.0-pr-107-2428.zip

VCST-848: Added public store property

---

src/VirtoCommerce.QuoteModule.Web/Scripts/blades/quotes-list.tpl.html

feat: Remove Counter from Search panel
https://virtocommerce.atlassian.net/browse/VCST-972
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.Quote_3.807.0-pr-110-2f7e.zip

VCST-972: Remove Counter from Search panel

---

src/VirtoCommerce.QuoteModule.Data/Services/QuoteRequestService.cs

https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.Quote_3.809.0-pr-108-c2a7.zip

Defining the logic of query construction and expression sorting in separate virtual methods

---

.github/workflows/module-ci.yml
.github/workflows/module-release-hotfix.yml
.github/workflows/publish-nugets.yml
.github/workflows/release.yml

https://virtocommerce.atlassian.net/browse/VCST-571
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.Quote_3.809.0-pr-111-f175.zip

VCST-571: Test workflows changes

---

src/VirtoCommerce.QuoteModule.Core/ModuleConstants.cs
src/VirtoCommerce.QuoteModule.Web/Localizations/en.VirtoCommerce.Quote.json

feat: Add FileUploadScopeName Public property. It allows to specify the scope name for file upload configurations and policies. Default: quote-attachments

VCST-18168: Add FileUploadScopeName public property.

---

src/VirtoCommerce.QuoteModule.ExperienceApi/VirtoCommerce.QuoteModule.ExperienceApi.csproj
src/VirtoCommerce.QuoteModule.Web/Module.cs
src/VirtoCommerce.QuoteModule.Web/module.manifest

Allows to request partial graphql by /ui/playground/quote
https://virtocommerce.atlassian.net/browse/VCST-2241
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.Quote_3.822.0-pr-128-593f.zip

VCST-2241: add scoped schema

---

Directory.Build.props
src/VirtoCommerce.QuoteModule.Core/Models/Address.cs
src/VirtoCommerce.QuoteModule.ExperienceApi/Commands/CreateQuoteFromCartCommandHandler.cs
src/VirtoCommerce.QuoteModule.ExperienceApi/Commands/QuoteCommand.cs
src/VirtoCommerce.QuoteModule.ExperienceApi/Commands/UpdateQuoteDynamicPropertiesCommand.cs
src/VirtoCommerce.QuoteModule.ExperienceApi/Schemas/InputQuoteAddressType.cs
src/VirtoCommerce.QuoteModule.ExperienceApi/Schemas/QuoteAddressType.cs
src/VirtoCommerce.QuoteModule.ExperienceApi/Schemas/QuoteAttachmentType.cs
src/VirtoCommerce.QuoteModule.ExperienceApi/Schemas/QuoteItemType.cs
src/VirtoCommerce.QuoteModule.ExperienceApi/Schemas/QuoteShipmentMethodType.cs
src/VirtoCommerce.QuoteModule.ExperienceApi/Schemas/QuoteTaxDetailType.cs
src/VirtoCommerce.QuoteModule.ExperienceApi/Schemas/QuoteTierPriceType.cs
src/VirtoCommerce.QuoteModule.ExperienceApi/Schemas/QuoteTotalsType.cs
src/VirtoCommerce.QuoteModule.ExperienceApi/Schemas/QuoteType.cs
src/VirtoCommerce.QuoteModule.ExperienceApi/VirtoCommerce.QuoteModule.ExperienceApi.csproj
src/VirtoCommerce.QuoteModule.Web/Module.cs
src/VirtoCommerce.QuoteModule.Web/module.manifest

https://virtocommerce.atlassian.net/browse/VCST-2376
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.Quote_3.900.0-pr-130-86e7.zip

VCST-2376: update GraphQL.NET to v8 

---

src/VirtoCommerce.QuoteModule.ExperienceApi/VirtoCommerce.QuoteModule.ExperienceApi.csproj
src/VirtoCommerce.QuoteModule.Web/module.manifest

https://virtocommerce.atlassian.net/browse/VCST-2589
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.Quote_3.902.0-pr-133-590d.zip

VCST-2589: update Xapi dependency (Mediatr)

---

src/VirtoCommerce.QuoteModule.Data.MySql/Migrations/20250606095327_RemoveRequiredFromAddressFields.Designer.cs
src/VirtoCommerce.QuoteModule.Data.MySql/Migrations/20250606095327_RemoveRequiredFromAddressFields.cs
src/VirtoCommerce.QuoteModule.Data.PostgreSql/Migrations/20250606095304_RemoveRequiredFromAddressFields.Designer.cs
src/VirtoCommerce.QuoteModule.Data.PostgreSql/Migrations/20250606095304_RemoveRequiredFromAddressFields.cs
src/VirtoCommerce.QuoteModule.Data.PostgreSql/Migrations/QuoteDbContextModelSnapshot.cs
src/VirtoCommerce.QuoteModule.Data.SqlServer/Migrations/20250606095359_RemoveRequiredFromAddressFields.Designer.cs
src/VirtoCommerce.QuoteModule.Data.SqlServer/Migrations/20250606095359_RemoveRequiredFromAddressFields.cs
src/VirtoCommerce.QuoteModule.Data.SqlServer/Migrations/QuoteDbContextModelSnapshot.cs
src/VirtoCommerce.QuoteModule.Data/Model/AddressEntity.cs
src/VirtoCommerce.QuoteModule.ExperienceApi/Schemas/InputQuoteAddressType.cs
src/VirtoCommerce.QuoteModule.ExperienceApi/Schemas/QuoteAddressType.cs

https://virtocommerce.atlassian.net/browse/VCST-3391
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.Quote_3.906.0-pr-138-bbf6.zip

VCST-3391: Remove Required attribute from FirstName and LastName in AddressEntity
